/* ===========================
   ARCHIVE JP — Shared Data
   Used by: main.js, person.js
   =========================== */

const ROLE_LABEL = {
  photographer:       "Photo",
  model:              "Model",
  stylist:            "Styling",
  hair_makeup:        "HM&UA",
  hair:               "Hair",
  makeup:             "Makeup",
  director:           "Director",
  videographer:       "Video Cam",
  editor:             "Edit",
  art_director:       "Art Dir.",
  creative_director:  "CD",
  casting:            "Casting",
  producer:           "Producer",
  set_designer:       "Set Design",
  retoucher:          "Retouch",
  other:              "Other",
};

const WORK_TYPES = [
  { id: "all",          label: "ALL",          labelJP: "すべて"       },
  { id: "look_book",    label: "LOOK BOOK",    labelJP: "LOOKブック"   },
  { id: "campaign",     label: "CAMPAIGN",     labelJP: "キャンペーン" },
  { id: "editorial",    label: "EDITORIAL",    labelJP: "エディトリアル" },
  { id: "video",        label: "VIDEO",        labelJP: "映像"         },
  { id: "special_page", label: "SPECIAL PAGE", labelJP: "特集ページ"   },
  { id: "event",        label: "EVENT",        labelJP: "イベント"     },
];

const CREDIT_ROLES_NAV = [
  { id: "photographer",      label: "Photographer",       count: 24 },
  { id: "model",             label: "Model",              count: 38 },
  { id: "stylist",           label: "Stylist",            count: 19 },
  { id: "hair_makeup",       label: "Hair & Makeup",      count: 15 },
  { id: "director",          label: "Director",           count: 8  },
  { id: "art_director",      label: "Art Director",       count: 11 },
  { id: "creative_director", label: "Creative Director",  count: 6  },
  { id: "retoucher",         label: "Retoucher",          count: 7  },
  { id: "set_designer",      label: "Set Designer",       count: 4  },
  { id: "casting",           label: "Casting",            count: 5  },
];

const agencies = [
  { id: "a1", name: "スペースクラフト",  type: "model",    website: "#" },
  { id: "a2", name: "イマージュ",        type: "model",    website: "#" },
  { id: "a3", name: "アース",            type: "model",    website: "#" },
  { id: "a4", name: "フロムファースト",  type: "creative", website: "#" },
  { id: "a5", name: "エルシーエー",      type: "creative", website: "#" },
  { id: "a6",   name: "テンカラット",      type: "model",    website: "#" },
  { id: "a-n8",    name: "NUMBER EIGHT",  type: "model", website: "https://numbereight-models.jp/", instagram_url: "https://www.instagram.com/numbereight_models/" },
  { id: "a-donna", name: "DONNA MODELS", type: "model", website: "http://www.donnamodels.jp/", instagram_url: "https://www.instagram.com/donnamodels.jp/" },
];

const brands = [
  { id: "b1",  name: "TOGA",             category: "womens",  works: 4 },
  { id: "b2",  name: "SACAI",            category: "unisex",  works: 3 },
  { id: "b3",  name: "HYKE",             category: "womens",  works: 3 },
  { id: "b4",  name: "ISSEY MIYAKE",     category: "unisex",  works: 5 },
  { id: "b5",  name: "Fumito Ganryu",    category: "mens",    works: 2 },
  { id: "b6",  name: "STUDIO NICHOLSON", category: "unisex",  works: 2 },
  { id: "b7",  name: "BEAMS",            category: "unisex",  works: 3 },
  { id: "b8",  name: "nest Robe",        category: "womens",  works: 4 },
  { id: "b9",  name: "YANUK",            category: "womens",  works: 3 },
  { id: "b10", name: "UNITED ARROWS",    category: "unisex",  works: 5 },
  { id: "b11", name: "IENA",             category: "womens",  works: 2 },
  { id: "b12", name: "SHISEIDO",         category: "beauty",  works: 2 },
];

const people = [
  {
    id: "p-keita",
    name: "ウツミ ケイタ", name_kana: "うつみ けいた", name_en: "Keita Utsumi",
    primary_role: "model", roles: ["model"],
    agency_id: "a-n8",
    tags: ["メンズ", "LOOKブック", "キャンペーン", "エディトリアル"],
    measurements: { height: 188, bust: 87, waist: 73, hip: 94, shoe: 28.5 },
    composite_url: "https://numbereight-models.jp/portfolio-item/keita-utsumi/",
    instagram_url: "https://www.instagram.com/mnik_ta/",
    profile_image: "https://numbereight-models.jp/wp-content/uploads/2020/09/TOP.jpg",
    portfolio_images: [
      "https://numbereight-models.jp/wp-content/uploads/2020/09/k9.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2020/09/K2-2.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2020/09/k2-3.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2020/09/IMG_6462.jpg",
    ],
    gender: "m", color: "#1A2030", is_verified: true,
  },
  {
    id: "p-jumpei",
    name: "岡﨑 順平", name_kana: "おかざき じゅんぺい", name_en: "Jumpei Okazaki",
    primary_role: "model", roles: ["model"],
    agency_id: "a-n8",
    tags: ["メンズ", "LOOKブック", "キャンペーン", "エディトリアル"],
    measurements: { height: 185, bust: 93, waist: 72, hip: 92.5, shoe: 28.0 },
    composite_url: "https://numbereight-models.jp/portfolio-item/jumpei-okazaki/",
    instagram_url: "https://www.instagram.com/jumpei_m1n/",
    profile_image: "https://numbereight-models.jp/wp-content/uploads/2021/06/1-のコピー-17.jpg",
    portfolio_images: [
      "https://numbereight-models.jp/wp-content/uploads/2021/06/2-7.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2021/06/o8.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2021/06/o14.jpg",
      "https://numbereight-models.jp/wp-content/uploads/2021/06/2-8.jpg",
    ],
    gender: "m", color: "#2A3040", is_verified: true,
  },
  {
    id: "p-yutong",
    name: "Yutong", name_en: "Yutong",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 75, waist: 62, hip: 89, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/yutong",
    instagram_url: "https://www.instagram.com/yutonhe_",
    profile_image: "https://cdn.syngency.com/138/models/435453/galleries/813882/large/22024007.jpg?1778147256",
    portfolio_images: [],
    gender: "f", color: "#2C2825", is_verified: true,
  },
  {
    id: "p-yuki-beniya",
    name: "Yuki Beniya", name_en: "Yuki Beniya",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 161, bust: 74, waist: 56, hip: 84, shoe: 24 },
    composite_url: "http://www.donnamodels.jp/portfolios/yuki-beniya",
    instagram_url: "https://www.instagram.com/yukibeniya",
    profile_image: "https://cdn.syngency.com/138/models/647298/galleries/1349790/large/22659545.jpg?1776937466",
    portfolio_images: [],
    gender: "f", color: "#1E1C1A", is_verified: true,
  },
  {
    id: "p-yuka-mannami",
    name: "Yuka Mannami", name_en: "Yuka Mannami",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 82, waist: 62, hip: 91, shoe: 24 },
    composite_url: "http://www.donnamodels.jp/portfolios/yuka-mannami",
    instagram_url: "https://www.instagram.com/yuka",
    profile_image: "https://cdn.syngency.com/138/models/36112/galleries/19071/large/19182795.jpg?1712819062",
    portfolio_images: [],
    gender: "f", color: "#1A1A18", is_verified: true,
  },
  {
    id: "p-tsugumi",
    name: "Tsugumi", name_en: "Tsugumi",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 78, waist: 59, hip: 88, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/tsugumi",
    instagram_url: "https://www.instagram.com/tsugumi_jp",
    profile_image: "https://cdn.syngency.com/138/models/63657/galleries/19046/large/20594957.jpg?1778487477",
    portfolio_images: [],
    gender: "f", color: "#201E1B", is_verified: true,
  },
  {
    id: "p-tao-okamoto",
    name: "岡本多緒", name_kana: "おかもと たお", name_en: "Tao Okamoto",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 80, waist: 58, hip: 84, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/tao-okamoto",
    instagram_url: "https://www.instagram.com/taookamoto",
    profile_image: "https://cdn.syngency.com/138/models/36109/galleries/6533/large/22456791.jpg?1773811783",
    portfolio_images: [],
    gender: "f", color: "#1C1C1C", is_verified: true,
  },
  {
    id: "p-natsumi-sekine",
    name: "Natsumi Sekine", name_en: "Natsumi Sekine",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 169, bust: 80, waist: 61, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/natsumi-sekine",
    instagram_url: "https://www.instagram.com/_n_a_t_s_u_m_i_",
    profile_image: "https://cdn.syngency.com/138/models/344954/galleries/611857/large/22728118.jpg?1778218298",
    portfolio_images: [],
    gender: "f", color: "#1D1B1A", is_verified: true,
  },
  {
    id: "p-maaya",
    name: "Maaya", name_en: "Maaya",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 175, bust: 80, waist: 61, hip: 90, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/maaya",
    instagram_url: "https://www.instagram.com/maaya_maaya3",
    profile_image: "https://cdn.syngency.com/138/models/36110/galleries/19038/large/207311.jpg?1713246184",
    portfolio_images: [],
    gender: "f", color: "#1B1B19", is_verified: true,
  },
  {
    id: "p-lala-takahashi",
    name: "Lala Takahashi", name_en: "Lala Takahashi",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 168, bust: 78, waist: 58, hip: 87, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/lala-takahashi",
    instagram_url: "https://www.instagram.com/lala__takahashi",
    profile_image: "https://cdn.syngency.com/138/models/103996/galleries/41878/large/22499453.jpg?1775099489",
    portfolio_images: [],
    gender: "f", color: "#1E1C1B", is_verified: true,
  },
  {
    id: "p-kido",
    name: "Kido", name_en: "Kido",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 77, waist: 59, hip: 89, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/kido",
    instagram_url: "https://www.instagram.com/kido_datura",
    profile_image: "https://cdn.syngency.com/138/models/473784/galleries/912529/large/22663661.jpg?1777005570",
    portfolio_images: [],
    gender: "f", color: "#1C1B1A", is_verified: true,
  },
  {
    id: "p-kayako-higuchi",
    name: "Kayako Higuchi", name_en: "Kayako Higuchi",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 181, bust: 82, waist: 60, hip: 89, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/kayako-higuchi",
    instagram_url: "https://www.instagram.com/ka.ya.ko",
    profile_image: "https://cdn.syngency.com/138/models/309262/galleries/393648/large/22269875.jpg?1772503406",
    portfolio_images: [],
    gender: "f", color: "#1A1A1A", is_verified: true,
  },
  {
    id: "p-hanaka",
    name: "Hanaka", name_en: "Hanaka",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 83, waist: 61, hip: 90, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/hanaka",
    instagram_url: "https://www.instagram.com/hanaka_h_",
    profile_image: "https://cdn.syngency.com/138/models/220801/galleries/195229/large/22632529.jpg?1776994672",
    portfolio_images: [],
    gender: "f", color: "#1E1B18", is_verified: true,
  },
  {
    id: "p-chiharu",
    name: "Chiharu", name_en: "Chiharu",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 80, waist: 60, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/chiharu",
    instagram_url: "https://www.instagram.com/chiharuokunugi",
    profile_image: "https://cdn.syngency.com/138/models/46811/galleries/19070/large/17031645.jpg?1770100197",
    portfolio_images: [],
    gender: "f", color: "#191919", is_verified: true,
  },
  {
    id: "p-asuka",
    name: "Asuka", name_en: "Asuka",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 180, bust: 76, waist: 59, hip: 89, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/asuka",
    instagram_url: "https://www.instagram.com/asukaa.__.99",
    profile_image: "https://cdn.syngency.com/138/models/606372/galleries/1280255/large/22658597.jpg?1776921424",
    portfolio_images: [],
    gender: "f", color: "#1B1A19", is_verified: true,
  },
  {
    id: "p-anna-kanehara",
    name: "Anna Kanehara", name_en: "Anna Kanehara",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 77, waist: 60, hip: 86, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/anna-kanehara",
    instagram_url: "https://www.instagram.com/Kitchenpharmacy",
    profile_image: "images/anna-kanehara-compcard.jpg",
    portfolio_images: [],
    gender: "f", color: "#1A1918", is_verified: true,
  },
  {
    id: "p-eunji-kwon",
    name: "Eunji Kwon", name_en: "Eunji Kwon",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 173, bust: 76, waist: 60, hip: 89, shoe: 24 },
    composite_url: "http://www.donnamodels.jp/portfolios/eunji-kwon",
    instagram_url: "https://www.instagram.com/ag__zi",
    profile_image: "https://cdn.syngency.com/138/models/1533624/galleries/2689553/large/22949951.jpg?1782459180",
    portfolio_images: [],
    gender: "f", color: "#191818", is_verified: true,
  },
  {
    id: "p-jenny-kot",
    name: "Jenny Kot", name_en: "Jenny Kot",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 76, waist: 58, hip: 86, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/jenny-kot",
    instagram_url: "https://www.instagram.com/kot_jenny",
    profile_image: "https://cdn.syngency.com/138/models/1522436/galleries/2654889/large/22920529.jpg?1781827964",
    portfolio_images: [],
    gender: "f", color: "#1A1919", is_verified: true,
  },
  {
    id: "p-sonja-ku",
    name: "Sonja Ku", name_en: "Sonja Ku",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 165, bust: 78, waist: 59, hip: 89, shoe: 23 },
    composite_url: "http://www.donnamodels.jp/portfolios/sonja-ku",
    instagram_url: "https://www.instagram.com/misssokates",
    profile_image: "images/sonja.jpg",
    portfolio_images: [],
    gender: "f", color: "#191818", is_verified: true,
  },
  {
    id: "p-joy",
    name: "Joy", name_en: "Joy",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 76, waist: 60, hip: 86, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/joy",
    profile_image: "https://cdn.syngency.com/138/models/1535752/galleries/2695886/large/22916371.jpg?1781778092",
    portfolio_images: [],
    gender: "f", color: "#1B1A19", is_verified: true,
  },
  {
    id: "p-amelie-loblich",
    name: "Amelie Loblich", name_en: "Amelie Loblich",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 76, waist: 59, hip: 88, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/amelie-loblich",
    profile_image: "https://cdn.syngency.com/138/models/1530853/galleries/2681256/large/22823378.jpg?1782202187",
    portfolio_images: [],
    gender: "f", color: "#1C1B1A", is_verified: true,
  },
  {
    id: "p-val-nova",
    name: "Val Nova", name_en: "Val Nova",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 82, waist: 60, hip: 89, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/val-nova",
    instagram_url: "https://www.instagram.com/viawlld",
    profile_image: "https://cdn.syngency.com/138/models/660203/galleries/1383058/large/22873293.jpg?1780977232",
    portfolio_images: [],
    gender: "f", color: "#1B1A18", is_verified: true,
  },
  {
    id: "p-aurore-franche",
    name: "Aurore Franche", name_en: "Aurore Franche",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 175, bust: 79, waist: 60, hip: 88, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/aurore-franche",
    instagram_url: "https://www.instagram.com/aurore.franche",
    profile_image: "https://cdn.syngency.com/138/models/154678/galleries/99638/large/1928206.jpg?1782105831",
    portfolio_images: [],
    gender: "f", color: "#1A1918", is_verified: true,
  },
  {
    id: "p-enija-narvaite",
    name: "Enija Narvaite", name_en: "Enija Narvaite",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 173, bust: 79, waist: 58, hip: 87, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/enija-narvaite",
    instagram_url: "https://www.instagram.com/enij.n",
    profile_image: "https://cdn.syngency.com/138/models/516102/galleries/989214/large/17688279.jpg?1779782951",
    portfolio_images: [],
    gender: "f", color: "#191818", is_verified: true,
  },
  {
    id: "p-veerle-van-der-krabben",
    name: "Veerle Van Der Krabben", name_en: "Veerle Van Der Krabben",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 173, bust: 81, waist: 60, hip: 89, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/veerle-van-der-krabben",
    instagram_url: "https://www.instagram.com/veerlevanderkrabben",
    profile_image: "https://cdn.syngency.com/138/models/1535486/galleries/2695076/large/22910608.jpg?1781667896",
    portfolio_images: [],
    gender: "f", color: "#1A1919", is_verified: true,
  },
  {
    id: "p-eliska-havlikova",
    name: "Eliska Havlikova", name_en: "Eliska Havlikova",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 78, waist: 60, hip: 88, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/eliska-havlikova",
    instagram_url: "https://www.instagram.com/eliska.havlikova",
    profile_image: "https://cdn.syngency.com/138/models/517512/galleries/992873/large/22748921.jpg?1778827520",
    portfolio_images: [],
    gender: "f", color: "#1B1A19", is_verified: true,
  },
  {
    id: "p-adele-chastanet",
    name: "Adele Chastanet", name_en: "Adele Chastanet",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 79, waist: 60, hip: 89, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/adele-chastanet",
    instagram_url: "https://www.instagram.com/adele_cnst",
    profile_image: "https://cdn.syngency.com/138/models/1524349/galleries/2660921/large/22768136.jpg?1779097890",
    portfolio_images: [],
    gender: "f", color: "#1A1918", is_verified: true,
  },
  {
    id: "p-marta-puchko",
    name: "Marta Puchko", name_en: "Marta Puchko",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 80, waist: 59, hip: 89, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/marta-puchko",
    profile_image: "https://cdn.syngency.com/138/models/1530052/galleries/2678028/large/22867601.jpg?1781062133",
    portfolio_images: [],
    gender: "f", color: "#1B1A19", is_verified: true,
  },
  {
    id: "p-petra-hegedues",
    name: "Petra Hegedues", name_en: "Petra Hegedues",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 173, bust: 78, waist: 60, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/petra-hegedues",
    instagram_url: "https://www.instagram.com/petrahegedus",
    profile_image: "https://cdn.syngency.com/138/models/69540/galleries/22168/large/15796567.jpg?1753242152",
    portfolio_images: [],
    gender: "f", color: "#1A1918", is_verified: true,
  },
  {
    id: "p-soizic-lagon",
    name: "Soizic Lagon", name_en: "Soizic Lagon",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 81, waist: 59, hip: 89, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/soizic-lagon",
    instagram_url: "https://www.instagram.com/_s0izic",
    profile_image: "https://cdn.syngency.com/138/models/460054/galleries/887866/large/21301435.jpg?1779446209",
    portfolio_images: [],
    gender: "f", color: "#1B1919", is_verified: true,
  },
  {
    id: "p-inga-markova",
    name: "Inga Markova", name_en: "Inga Markova",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 172, bust: 80, waist: 58, hip: 88, shoe: 24 },
    composite_url: "http://www.donnamodels.jp/portfolios/inga-markova",
    instagram_url: "https://www.instagram.com/ingamarkovva",
    profile_image: "https://cdn.syngency.com/138/models/1461824/galleries/2409172/large/22903805.jpg?1781589221",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-maria-sosa",
    name: "Maria Sosa", name_en: "Maria Sosa",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 175, bust: 75, waist: 58, hip: 86, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/maria-sosa",
    instagram_url: "https://www.instagram.com/mariiiasosa099",
    profile_image: "https://cdn.syngency.com/138/models/522918/galleries/1030772/large/20169722.jpg?1771558113",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-kira-zhurakovska",
    name: "Kira Zhurakovska", name_en: "Kira Zhurakovska",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 172, bust: 76, waist: 58, hip: 87, shoe: 24 },
    composite_url: "http://www.donnamodels.jp/portfolios/kira-zhurakovska",
    instagram_url: "https://www.instagram.com/kira_zhura",
    profile_image: "https://cdn.syngency.com/138/models/429426/galleries/799086/large/20607007.jpg?1773369547",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-cicelle-hoppal",
    name: "Cicelle Hoppal", name_en: "Cicelle Hoppal",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 78, waist: 60, hip: 89, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/cicelle-hoppal",
    instagram_url: null,
    profile_image: "https://cdn.syngency.com/138/models/673515/galleries/1410344/large/20782959.jpg?1781581314",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-reilly-mullins",
    name: "Reilly Mullins", name_en: "Reilly Mullins",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 81, waist: 60, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/reilly-mullins",
    instagram_url: "https://www.instagram.com/reilly.m.official",
    profile_image: "https://cdn.syngency.com/138/models/677825/galleries/1424409/large/20910662.jpg?1777772690",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-sime-ferreira",
    name: "Sime Ferreira", name_en: "Sime Ferreira",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 80, waist: 60, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/sime-ferreira",
    instagram_url: "https://www.instagram.com/simeeeeef",
    profile_image: "https://cdn.syngency.com/138/models/589909/galleries/1199363/large/19419915.jpg?1717144806",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-daria-baryshnikova",
    name: "Daria Baryshnikova", name_en: "Daria Baryshnikova",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 174, bust: 78, waist: 58, hip: 86, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/daria-baryshnikova",
    instagram_url: "https://www.instagram.com/daria_baryshnikova",
    profile_image: "https://cdn.syngency.com/138/models/1521002/galleries/2648372/large/22591641.jpg?1778470693",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-loras",
    name: "Loras", name_en: "Loras",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 78, waist: 60, hip: 87, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/loras",
    instagram_url: "https://www.instagram.com/loras.petrovska",
    profile_image: "https://cdn.syngency.com/138/models/1517790/galleries/2643139/large/22768276.jpg?1779099455",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-gabriela-kuusk",
    name: "Gabriela Kuusk", name_en: "Gabriela Kuusk",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 75, waist: 60, hip: 86, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/gabriela-kuusk",
    instagram_url: "https://www.instagram.com/gabrielakuusk",
    profile_image: "https://cdn.syngency.com/138/models/1518401/galleries/2639949/large/22741876.jpg?1782469429",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-anick-chan",
    name: "Anick Chan", name_en: "Anick Chan",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 80, waist: 60, hip: 87, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/anick-chan",
    instagram_url: "https://www.instagram.com/anick_chan",
    profile_image: "https://cdn.syngency.com/138/models/656773/galleries/1396742/large/20637334.jpg?1776156215",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-maya-dzipanow",
    name: "Maya Dzipanow", name_en: "Maya Dzipanow",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 80, waist: 58, hip: 87, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/maya-dzipanow",
    instagram_url: "https://www.instagram.com/majadzipanow",
    profile_image: "https://cdn.syngency.com/138/models/1504687/galleries/2600434/large/22244006.jpg?1780987361",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-anna-cichon",
    name: "Anna Cichon", name_en: "Anna Cichon",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 173, bust: 79, waist: 60, hip: 89, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/anna-cichon",
    instagram_url: "https://www.instagram.com/annacichonn",
    profile_image: "https://cdn.syngency.com/138/models/678210/galleries/1425858/large/22879203.jpg?1782295190",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-hanna-nilsson",
    name: "Hanna Nilsson", name_en: "Hanna Nilsson",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 77, waist: 57, hip: 87, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/hanna-nilsson",
    instagram_url: "https://www.instagram.com/hannaellisabeth",
    profile_image: "https://cdn.syngency.com/138/models/1527970/galleries/2672068/large/22873109.jpg?1780974941",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-mira-malomsoky",
    name: "Mira Malomsoky", name_en: "Mira Malomsoky",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 79, waist: 58, hip: 87, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/mira-malomsoky",
    instagram_url: "https://www.instagram.com/malomsoky_mira",
    profile_image: "https://cdn.syngency.com/138/models/1522456/galleries/2654960/large/22646510.jpg?1776938808",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-maia-zschach",
    name: "Maia Zschach", name_en: "Maia Zschach",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 77, waist: 60, hip: 86, shoe: 25 },
    composite_url: "http://www.donnamodels.jp/portfolios/maia-zschach",
    instagram_url: "https://www.instagram.com/maia.zschach",
    profile_image: "https://cdn.syngency.com/138/models/1528868/galleries/2674331/large/22949976.jpg?1782463963",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-darina-iandusheva",
    name: "Darina Iandusheva", name_en: "Darina Iandusheva",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 179, bust: 81, waist: 60, hip: 88, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/darina-iandusheva",
    instagram_url: "https://www.instagram.com/darina_iandusheva",
    profile_image: "https://cdn.syngency.com/138/models/1523811/galleries/2659233/large/22676096.jpg?1781578525",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-malin-jansson",
    name: "Malin Jansson", name_en: "Malin Jansson",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 80, waist: 60, hip: 87, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/malin-jansson",
    instagram_url: null,
    profile_image: "https://cdn.syngency.com/138/models/1529349/galleries/2675942/large/22949958.jpg?1782458380",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-rita-santos",
    name: "Rita Santos", name_en: "Rita Santos",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 81, waist: 60, hip: 89, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/rita-santos",
    instagram_url: "https://www.instagram.com/ritafmsantos",
    profile_image: "https://cdn.syngency.com/138/models/678426/galleries/1427060/large/22797958.jpg?1781693741",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-viktorija",
    name: "Viktorija", name_en: "Viktorija",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 177, bust: 78, waist: 58, hip: 89, shoe: 26 },
    composite_url: "http://www.donnamodels.jp/portfolios/viktorija",
    instagram_url: "https://www.instagram.com/viktorija_vitkauskaite",
    profile_image: "https://cdn.syngency.com/138/models/681160/galleries/2374984/large/20987522.jpg?1782381372",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-natalia-anna-wilk",
    name: "Natalia Anna Wilk", name_en: "Natalia Anna Wilk",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 175, bust: 74, waist: 59, hip: 88, shoe: 24.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/natalia-anna-wilk",
    instagram_url: "https://www.instagram.com/wilknataliae",
    profile_image: "https://cdn.syngency.com/138/models/1527109/galleries/2669534/large/22834444.jpg?1780541024",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
  {
    id: "p-aine-oleary",
    name: "Aine O'Leary", name_en: "Aine O'Leary",
    primary_role: "model", roles: ["model"],
    agency_id: "a-donna",
    measurements: { height: 176, bust: 78, waist: 58, hip: 86, shoe: 25.5 },
    composite_url: "http://www.donnamodels.jp/portfolios/aine-oleary",
    instagram_url: "https://www.instagram.com/aineolearyy",
    profile_image: "https://cdn.syngency.com/138/models/1522190/galleries/2653370/large/22867619.jpg?1780912805",
    portfolio_images: [],
    gender: "f", color: "#1A1818", is_verified: true,
  },
];

const works = [
  {
    id: "w1", title: "2026AW LOOK BOOK",
    type: "look_book", brand_id: "b1", brand: "TOGA", season: "2026AW", year: 2026,
    tags: ["コンテンポラリー", "スタジオ撮影", "モノトーン"],
    is_published: true, featured: true, color: "#1E1E1C", accent: "#C0A070",
    credits: [
      { credit_role: "photographer", person: "中村 浩一",        order_index: 1 },
      { credit_role: "stylist",      person: "渡辺 幸子",        order_index: 1 },
      { credit_role: "hair_makeup",  person: "石川 智子",        order_index: 1 },
      { credit_role: "model",        person: "青木 優里",        order_index: 1 },
      { credit_role: "model",        person: "田中 葵",          order_index: 2 },
      { credit_role: "retoucher",    person: "デジタルアーツ 東京", order_index: 1 },
    ],
  },
  {
    id: "w2", title: "SS26 CAMPAIGN VISUAL",
    type: "campaign", brand_id: "b2", brand: "SACAI", season: "2026SS", year: 2026,
    tags: ["広告", "アーバン", "モード"],
    is_published: true, featured: true, color: "#14141C", accent: "#7878A8",
    credits: [
      { credit_role: "photographer",      person: "伊藤 隆",          order_index: 1 },
      { credit_role: "stylist",           person: "渡辺 幸子",        order_index: 1 },
      { credit_role: "creative_director", person: "阿部 千登勢",      order_index: 1 },
      { credit_role: "hair_makeup",       person: "石川 智子",        order_index: 1 },
      { credit_role: "model",             person: "青木 優里",        order_index: 1 },
      { credit_role: "retoucher",         person: "デジタルアーツ 東京", order_index: 1 },
    ],
  },
  {
    id: "w3", title: "KNITWEAR COLLECTION FILM",
    type: "video", brand_id: "b5", brand: "Fumito Ganryu", season: "2025AW", year: 2025,
    tags: ["コレクションフィルム", "ニット", "映像"],
    is_published: true, featured: false, color: "#1A2418", accent: "#6A8868",
    credits: [
      { credit_role: "director",     person: "木村 慎",   order_index: 1 },
      { credit_role: "videographer", person: "坂本 健",   order_index: 1 },
      { credit_role: "stylist",      person: "鈴木 真由", order_index: 1 },
      { credit_role: "hair_makeup",  person: "武田 恵",   order_index: 1 },
      { credit_role: "model",        person: "松本 愛",   order_index: 1 },
    ],
  },
  {
    id: "w4", title: "SPRING BEAUTY CLOSE-UP",
    type: "editorial", brand_id: "b12", brand: "SHISEIDO", season: "2026SS", year: 2026,
    tags: ["ビューティー", "クローズアップ", "春"],
    is_published: true, featured: false, color: "#281818", accent: "#B87878",
    credits: [
      { credit_role: "photographer",  person: "中村 浩一", order_index: 1 },
      { credit_role: "hair",          person: "高橋 彩",   order_index: 1 },
      { credit_role: "makeup",        person: "武田 恵",   order_index: 1 },
      { credit_role: "model",         person: "伊藤 七海", order_index: 1 },
      { credit_role: "art_director",  person: "渡辺 幸子", order_index: 1 },
    ],
  },
  {
    id: "w5", title: "STREET CASTING — SHIBUYA",
    type: "editorial", brand_id: "b7", brand: "BEAMS", season: "2026SS", year: 2026,
    tags: ["ストリートキャスティング", "渋谷", "スナップ"],
    is_published: true, featured: false, color: "#101828", accent: "#5A7AA8",
    credits: [
      { credit_role: "photographer", person: "坂本 健",     order_index: 1 },
      { credit_role: "stylist",      person: "長谷川 亜紀", order_index: 1 },
      { credit_role: "casting",      person: "フロムファースト", order_index: 1 },
      { credit_role: "model",        person: "公募モデル 12名", order_index: 1 },
    ],
  },
  {
    id: "w6", title: "次世代スタイリスト特集",
    type: "special_page", brand_id: null, brand: null, season: "2025", year: 2025,
    tags: ["特集", "スタイリスト", "インタビュー"],
    is_published: true, featured: false, color: "#201808", accent: "#B89048",
    credits: [
      { credit_role: "photographer", person: "山田 拓海",  order_index: 1 },
      { credit_role: "photographer", person: "坂本 健",    order_index: 2 },
      { credit_role: "stylist",      person: "鈴木 真由",  order_index: 1 },
      { credit_role: "stylist",      person: "長谷川 亜紀", order_index: 2 },
    ],
  },
  {
    id: "w7", title: "2025AW LOOK BOOK",
    type: "look_book", brand_id: "b8", brand: "nest Robe", season: "2025AW", year: 2025,
    tags: ["ナチュラル", "リネン", "屋外撮影"],
    is_published: true, featured: false, color: "#282018", accent: "#A89060",
    credits: [
      { credit_role: "photographer", person: "山田 拓海", order_index: 1 },
      { credit_role: "stylist",      person: "小林 美穂", order_index: 1 },
      { credit_role: "hair_makeup",  person: "高橋 彩",   order_index: 1 },
      { credit_role: "model",        person: "松本 愛",   order_index: 1 },
      { credit_role: "model",        person: "田中 葵",   order_index: 2 },
    ],
  },
  {
    id: "w8", title: "HAIR ARCHIVE 2025",
    type: "editorial", brand_id: "b12", brand: "SHISEIDO", season: "2025", year: 2025,
    tags: ["ヘア", "ビューティー", "アーカイブ"],
    is_published: true, featured: false, color: "#200A10", accent: "#A87878",
    credits: [
      { credit_role: "photographer", person: "木下 裕二", order_index: 1 },
      { credit_role: "hair",         person: "高橋 彩",   order_index: 1 },
      { credit_role: "model",        person: "田中 葵",   order_index: 1 },
      { credit_role: "model",        person: "伊藤 七海", order_index: 2 },
    ],
  },
  {
    id: "w9", title: "AW25 LOOK BOOK",
    type: "look_book", brand_id: "b6", brand: "STUDIO NICHOLSON", season: "2025AW", year: 2025,
    tags: ["エシカル", "ミニマル", "ロンドン"],
    is_published: true, featured: false, color: "#101A10", accent: "#608060",
    credits: [
      { credit_role: "photographer", person: "山田 拓海", order_index: 1 },
      { credit_role: "stylist",      person: "小林 美穂", order_index: 1 },
      { credit_role: "hair_makeup",  person: "武田 恵",   order_index: 1 },
      { credit_role: "model",        person: "松本 愛",   order_index: 1 },
    ],
  },
  {
    id: "w10", title: "DIGITAL FASHION FILM",
    type: "video", brand_id: "b4", brand: "ISSEY MIYAKE", season: "2025AW", year: 2025,
    tags: ["コレクションフィルム", "デジタル", "映像"],
    is_published: true, featured: false, color: "#08080F", accent: "#506888",
    credits: [
      { credit_role: "director",     person: "木村 慎",   order_index: 1 },
      { credit_role: "videographer", person: "伊藤 隆",   order_index: 1 },
      { credit_role: "stylist",      person: "渡辺 幸子", order_index: 1 },
      { credit_role: "hair_makeup",  person: "石川 智子", order_index: 1 },
      { credit_role: "model",        person: "田中 葵",   order_index: 1 },
      { credit_role: "editor",       person: "タケウチ 映像編集", order_index: 1 },
    ],
  },
  {
    id: "w11", title: "スタイリスト特集：渡辺 幸子",
    type: "special_page", brand_id: null, brand: null, season: "2025", year: 2025,
    tags: ["特集", "インタビュー", "スタイリスト"],
    is_published: true, featured: false, color: "#180E04", accent: "#907040",
    credits: [
      { credit_role: "photographer", person: "中村 浩一", order_index: 1 },
      { credit_role: "stylist",      person: "渡辺 幸子", order_index: 1 },
    ],
  },
  {
    id: "w12", title: "POP-UP EVENT VISUAL",
    type: "event", brand_id: "b9", brand: "YANUK", season: "2026SS", year: 2026,
    tags: ["ポップアップ", "イベント", "デニム"],
    is_published: true, featured: false, color: "#101020", accent: "#485880",
    credits: [
      { credit_role: "photographer",  person: "坂本 健",     order_index: 1 },
      { credit_role: "stylist",       person: "長谷川 亜紀", order_index: 1 },
      { credit_role: "hair_makeup",   person: "武田 恵",     order_index: 1 },
      { credit_role: "model",         person: "青木 優里",   order_index: 1 },
      { credit_role: "set_designer",  person: "山下スタジオ", order_index: 1 },
      { credit_role: "producer",      person: "川田 裕子",   order_index: 1 },
    ],
  },

  // ── Jumpei Okazaki works ──
  {
    id: "wj1", title: "2021AW LOOK BOOK",
    type: "look_book", brand_id: null, brand: "CLANE HOMME", season: "2021AW", year: 2021,
    tags: ["メンズ", "スタジオ", "モノトーン"],
    is_published: true, featured: false, color: "#1A1A18", accent: "#888878",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2021/06/j1-4-249x300.jpg",
    credits: [
      { credit_role: "photographer",  person: "中村 浩一",  order_index: 1 },
      { credit_role: "stylist",       person: "渡辺 幸子",  order_index: 1 },
      { credit_role: "hair_makeup",   person: "石川 智子",  order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
    ],
  },
  {
    id: "wj2", title: "OUTDOOR COLLECTION",
    type: "editorial", brand_id: null, brand: "UNITED ARROWS", season: "2021SS", year: 2021,
    tags: ["アウトドア", "カジュアル", "屋外"],
    is_published: true, featured: false, color: "#182010", accent: "#708060",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2021/06/o1-1-249x300.jpg",
    credits: [
      { credit_role: "photographer",  person: "坂本 健",    order_index: 1 },
      { credit_role: "stylist",       person: "小林 美穂",  order_index: 1 },
      { credit_role: "hair_makeup",   person: "高橋 彩",    order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
    ],
  },
  {
    id: "wj3", title: "MEN'S FUDGE — FEATURE",
    type: "editorial", brand_id: null, brand: "Men's FUDGE", season: "2021 No.112", year: 2021,
    tags: ["エディトリアル", "雑誌", "メンズ"],
    is_published: true, featured: false, color: "#201830", accent: "#887898",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2021/06/j3-2-249x300.jpg",
    credits: [
      { credit_role: "photographer",  person: "山田 拓海",  order_index: 1 },
      { credit_role: "stylist",       person: "渡辺 幸子",  order_index: 1 },
      { credit_role: "hair_makeup",   person: "石川 智子",  order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
      { credit_role: "art_director",  person: "渡辺 幸子",  order_index: 1 },
    ],
  },
  {
    id: "wj4", title: "SS21 CAMPAIGN",
    type: "campaign", brand_id: null, brand: "SHIPS", season: "2021SS", year: 2021,
    tags: ["キャンペーン", "広告", "ライフスタイル"],
    is_published: true, featured: false, color: "#101820", accent: "#506878",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2021/06/j6-1-249x300.jpg",
    credits: [
      { credit_role: "photographer",  person: "伊藤 隆",    order_index: 1 },
      { credit_role: "stylist",       person: "小林 美穂",  order_index: 1 },
      { credit_role: "hair_makeup",   person: "高橋 彩",    order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
      { credit_role: "producer",      person: "川田 裕子",  order_index: 1 },
    ],
  },
  {
    id: "wj5", title: "BRAND VISUAL",
    type: "campaign", brand_id: null, brand: "MIOKO", season: "2021SS", year: 2021,
    tags: ["ブランドビジュアル", "コンテンポラリー"],
    is_published: true, featured: false, color: "#201010", accent: "#987060",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2021/06/MIOKO-249x300.jpg",
    credits: [
      { credit_role: "photographer",  person: "中村 浩一",  order_index: 1 },
      { credit_role: "stylist",       person: "渡辺 幸子",  order_index: 1 },
      { credit_role: "hair_makeup",   person: "石川 智子",  order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
      { credit_role: "creative_director", person: "阿部 千登勢", order_index: 1 },
    ],
  },
  {
    id: "wj6", title: "AGENCY BOOK 2025",
    type: "look_book", brand_id: null, brand: "NUMBER EIGHT MODELS", season: "2025", year: 2025,
    tags: ["エージェンシーブック", "ポートレート"],
    is_published: true, featured: false, color: "#141820", accent: "#607090",
    image_url: "https://numbereight-models.jp/wp-content/uploads/2025/03/%E5%B2%A1%E5%B4%8E%E9%A0%86%E5%B9%B3%E3%80%90NUMBER-EIGHT%E3%80%91F-1024x724.jpg",
    credits: [
      { credit_role: "photographer",  person: "木下 裕二",  order_index: 1 },
      { credit_role: "model",         person: "岡﨑 順平",  order_index: 1 },
    ],
  },
];

// ── Shared helpers ──

function groupCredits(credits) {
  const order = ["photographer","art_director","creative_director","stylist",
    "hair_makeup","hair","makeup","model","director","videographer",
    "editor","set_designer","retoucher","producer","casting","other"];
  const grouped = {};
  credits.forEach(c => {
    if (!grouped[c.credit_role]) grouped[c.credit_role] = [];
    grouped[c.credit_role].push(c.person);
  });
  return order.filter(r => grouped[r]).map(r => ({ role: r, people: grouped[r] }));
}

function getWorkColor(type) {
  const map = {
    look_book:    "var(--type-look)",
    campaign:     "var(--type-campaign)",
    editorial:    "var(--type-editorial)",
    video:        "var(--type-video)",
    special_page: "var(--type-special)",
    event:        "var(--type-event)",
  };
  return map[type] || "var(--text-muted)";
}

function buildCreditNameHTML(name, linkPrefix) {
  const match = people.find(p => p.name === name);
  if (!match) return `<span class="credit-name">${name}</span>`;

  const agency = match.agency_id ? agencies.find(a => a.id === match.agency_id) : null;
  const agencyBadge = agency
    ? ` <a class="credit-agency-tag" href="${linkPrefix}agency.html?id=${agency.id}">${agency.name}</a>`
    : "";

  return `<a class="credit-name credit-link" href="${linkPrefix}person.html?id=${match.id}">${name}</a>${agencyBadge}`;
}
